project:
  type: website

website:
  title: "Yumeka Nagano"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: sac.qmd

format:
  html:
    theme: cosmo